% Saves the stimulus condition matfile in a few different different ways to
% use in bids GLM summary code. This only needs to be run once.

% All stimulus conditions
allConditions = {...
    'HRFPATTERN'...
    'CRF-1' ...
    'CRF-2' ...
    'CRF-3' ...
    'CRF-4' ...
    'CRF-5' ...
    'GRATING' ...
    'PLAID' ...
    'CIRCULAR' ...
    'SPARSITY-1' ...
    'SPARSITY-2' ...
    'SPARSITY-3' ...
    'SPARSITY-4' ...
    'ONEPULSE-1' ...
    'ONEPULSE-2' ...
    'ONEPULSE-3' ...
    'ONEPULSE-4' ...
    'ONEPULSE-5' ...
    'ONEPULSE-6' ...
    'TWOPULSE-1' ...
    'TWOPULSE-2' ...
    'TWOPULSE-3' ...
    'TWOPULSE-4' ...
    'TWOPULSE-5' ...
    'TWOPULSE-6' ...
    'FACES' ...
    'LETTERS' ...
    'HOUSES' ...
    };
% In case it's useful, save the stimulus condition numbers
conditionNums = {1 107   108   109   110   111   112   113   114   115   116 ...
    117   118     119   120   121   122   123  ...
    124   125   126   127   128   129   130 131   132   133};

% Make some subsets for plotting
conditionSubsets          = [];
conditionSubsets.crf      = {'CRF-1', 'CRF-2','CRF-3', 'CRF-4','CRF-5'};
conditionSubsets.pattern  = {'GRATING','PLAID','CIRCULAR'};
conditionSubsets.sparsity = {'SPARSITY-1','SPARSITY-2','SPARSITY-3','SPARSITY-4'};
conditionSubsets.onepulse = {'ONEPULSE-1','ONEPULSE-2','ONEPULSE-3','ONEPULSE-4','ONEPULSE-5','ONEPULSE-6'};
conditionSubsets.twopulse = {'TWOPULSE-1','TWOPULSE-2','TWOPULSE-3','TWOPULSE-4','TWOPULSE-5','TWOPULSE-6'};
conditionSubsets.objects  = {'FACES','LETTERS','HOUSES'};

% Make subsets by experiment
temporalpattern = {'ONEPULSE-1','ONEPULSE-2','ONEPULSE-3','ONEPULSE-4'...
    'ONEPULSE-5','ONEPULSE-6', 'TWOPULSE-1','TWOPULSE-2',...
    'TWOPULSE-3','TWOPULSE-4' ,'TWOPULSE-5','TWOPULSE-6'};
spatialobject = {'FACES','LETTERS','HOUSES'};
spatialpattern = {'CRF-1', 'CRF-2','CRF-3', 'CRF-4','CRF-5',...
    'GRATING','PLAID','CIRCULAR','SPARSITY-1','SPARSITY-2',...
    'SPARSITY-3','SPARSITY-4'};

save ('designMatrixConditions.mat', 'allConditions', 'conditionSubsets', ...
    'conditionNums', 'temporalpattern','spatialobject', 'spatialpattern' )
